tasks:
  - init: >
      yarn install &&
      yarn run build &&
      yarn test
      cd examples/manifold
      yarn
      npm run start
    name: split-term
  - command: echo split
    openMode: split-right
ports:
  - port: 8080
    onOpen: open-preview
