tasks:
  - init: >
      cd examples/manifold &&
      npm install &&
      npm run start
    name: split-term
  - command: >
      yarn install &&
      yarn test
    openMode: split-right
ports:
  - port: 8080
    onOpen: open-preview
